[package]
name = "limage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
limage_core = { path = "./limage_core" }
shiterators = { path = "./shiterators" }
