name: Main Checks

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - name: Lint features
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- --deny=warnings

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- --deny=warnings

  clippy-release:
    name: Clippy release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - name: Lint features
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --release --all-targets -- --deny=warnings

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --release --all-targets --all-features -- --deny=warnings

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-nextest

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run
